Battle_SetTurnInfo(BATTLE_TURN.TIME,6000000);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_DOWN,20); 
Battle_SetTurnInfo(BATTLE_TURN.BOARD_UP,40);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_LEFT,30);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_RIGHT,30);
