Battle_SetTurnInfo(BATTLE_TURN.TIME,6000000);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_LEFT,180);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_RIGHT,180);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_DOWN,65); 
Battle_SetTurnInfo(BATTLE_TURN.BOARD_UP,65);
