Battle_SetTurnInfo(BATTLE_TURN.TIME,6000000);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_DOWN,70); 
Battle_SetTurnInfo(BATTLE_TURN.BOARD_UP,110);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_LEFT,150);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_RIGHT,150);