Battle_SetTurnInfo(BATTLE_TURN.TIME,600000);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_DOWN,65); 
Battle_SetTurnInfo(BATTLE_TURN.BOARD_UP,100);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_LEFT,150);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_RIGHT,150);
