Battle_SetTurnInfo(BATTLE_TURN.TIME,600);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_DOWN,65); 
Battle_SetTurnInfo(BATTLE_TURN.BOARD_UP,65);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_LEFT,150);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_RIGHT,150);