Battle_SetTurnInfo(BATTLE_TURN.TIME,6000000);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_LEFT,72.5);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_RIGHT,72.5);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_UP,75);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_DOWN,65);
