Battle_SetTurnInfo(BATTLE_TURN.TIME,-1);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_LEFT,72.5);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_RIGHT,73.5);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_UP,83);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_DOWN,63);
